### ISSUE TITLE
Bug on windows

### ISSUE THREAD

**Issue by blackneeed** [z-izz/ziv#2]
When i run the windows executable (i have a 64-bit system)
it just doesn't launch

**Comment by prescott2m** [comment]
Sorry for not seeing your issue, going to try to see what causes it asap

**Comment by prescott2m** [comment]
Your issue here is most likely that you're launching ziv by double-clicking the .exe file in the Windows GUI, you cannot do this. ziv is primarily designed to run in CMD, and expects a file to edit as a parameter. That being said, you can launch ziv through GUI by dragging the file you want to edit, over the ziv-win64.exe file, and it should launch and be editing the file.

You also need .NET 7.0.16 for ziv to run on Windows, so also install that.

**Comment by blackneeed** [comment]
Ik, i figured that out later, still it crashes gonna provide what it prints later

**Comment by blackneeed** [comment]
Later today

**Comment by blackneeed** [comment]
Oh, it works, idk why it didnt work on w10
